plugins {
    id 'com.android.library'
}

android {
    namespace = 'com.github.tvbox.quickjs'
    compileSdk = 36

    defaultConfig {
        minSdk = 23
        targetSdk = 30
    }
    lint {
        disable 'UnsafeOptInUsageError'
    }
}

dependencies {
   api 'wang.harlon.quickjs:wrapper-android:3.2.3' 
}
