plugins {
    id 'com.android.library'
}

android {
    namespace = 'com.github.tvbox.quickjs'
    compileSdk = 36

    defaultConfig {
        minSdk = 23
        targetSdk = 28
    }
}

dependencies {
    api 'wang.harlon.quickjs:wrapper-android:3.2.3'
    api 'wang.harlon.quickjs:wrapper-java:3.2.3' 
}
